[2024-09-05T15:22:10.100+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T15:22:10.139+0530] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_data manual__2024-09-05T09:38:45.981858+00:00 [queued]>
[2024-09-05T15:22:10.156+0530] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_data manual__2024-09-05T09:38:45.981858+00:00 [queued]>
[2024-09-05T15:22:10.158+0530] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T15:22:10.549+0530] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-09-05 09:38:45.981858+00:00
[2024-09-05T15:22:10.558+0530] {standard_task_runner.py:72} INFO - Started process 76615 to run task
[2024-09-05T15:22:10.581+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline', 'preprocess_data', 'manual__2024-09-05T09:38:45.981858+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/aasampledag.py', '--cfg-path', '/tmp/tmpj2j5z712']
[2024-09-05T15:22:10.587+0530] {standard_task_runner.py:105} INFO - Job 11: Subtask preprocess_data
[2024-09-05T15:22:11.078+0530] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline.preprocess_data manual__2024-09-05T09:38:45.981858+00:00 [running]> on host 01-011889.idsil.loc
[2024-09-05T15:22:11.616+0530] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T09:38:45.981858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-05T09:38:45.981858+00:00'
[2024-09-05T15:22:11.622+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-05T15:22:11.625+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-05T15:22:11.627+0530] {logging_mixin.py:190} INFO - Current task name:preprocess_data state:running start_date:2024-09-05 09:52:10.141829+00:00
[2024-09-05T15:22:11.629+0530] {logging_mixin.py:190} INFO - Dag name:ml_pipeline and current dag run status:running
[2024-09-05T15:22:11.631+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T15:22:14.408+0530] {xcom.py:690} ERROR - Object of type Series is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-09-05T15:22:14.418+0530] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/aasampledag.py", line 22, in preprocess_data
    kwargs['ti'].xcom_push(key='y_train', value=y_train)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3629, in xcom_push
    XCom.set(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2024-09-05T15:22:14.763+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-05T15:22:14.773+0530] {logging_mixin.py:190} INFO - Task start:2024-09-05 09:52:10.141829+00:00 end:2024-09-05 09:52:14.761254+00:00 duration:4.619425
[2024-09-05T15:22:14.781+0530] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): preprocess_data> dag:<DAG: ml_pipeline> dagrun:<DagRun ml_pipeline @ 2024-09-05 09:38:45.981858+00:00: manual__2024-09-05T09:38:45.981858+00:00, state:running, queued_at: 2024-09-05 09:38:46.473977+00:00. externally triggered: True>
[2024-09-05T15:22:14.791+0530] {logging_mixin.py:190} INFO - Failure caused by Object of type Series is not JSON serializable
[2024-09-05T15:22:14.794+0530] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=preprocess_data, run_id=manual__2024-09-05T09:38:45.981858+00:00, execution_date=20240905T093845, start_date=20240905T095210, end_date=20240905T095214
[2024-09-05T15:22:14.959+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T15:22:14.964+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task preprocess_data (Object of type Series is not JSON serializable; 76615)
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/aasampledag.py", line 22, in preprocess_data
    kwargs['ti'].xcom_push(key='y_train', value=y_train)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3629, in xcom_push
    XCom.set(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2024-09-05T15:22:15.078+0530] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-05T15:22:15.127+0530] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-05T15:22:15.133+0530] {local_task_job_runner.py:240} INFO - ::endgroup::
